const customAttackNames = {
  Phy: "Físico",
  Mag: "Magia",
  Fire: "Fuego",
  Ligt: "Rayo",
  Holy: "Sagrado",
  Sor: "Encantamiento",
  Crit: "Crítico",
  Rng: "Rango",
};

const customAttributeNames = {
  Str: "Fuerza",
  Dex: "Destreza",
  Int: "Inteligencia",
  Fai: "Fe",
  Arc: "Arcano",
};

const customCategoryNames = {
  Axe: "Hacha",
  Bow: "Arco",
  Ballista: "Balista",
  Claw: "Garras",
  "Colossal Sword": "Espada colosal",
  "Colossal Weapon": "Arma colosal",
  Crossbow: "Ballesta",
  "Curved Greatsword": "Espadón curvo",
  "Curved Sword": "Espada curva",
  Dagger: "Daga",
  Fist: "Puños",
  Flail: "Mayal",
  "Glintstone Staff": "Bastón de piedra refulgente",
  Greataxe: "Gran hacha",
  Greatbow: "Arco grande",
  "Great Spear": "Lanza larga",
  Greatsword: "Espadón",
  Halberd: "Alabarda",
  Hammer: "Martillo",
  "Heavy Thrusting Sword": "Espada de embestida pesada",
  "Light Bow": "Arco ligero",
  Reaper: "Guadaña",
  "Sacred Seal": "Sello sagrado",
  Spear: "Lanza",
  "Straight Sword": "Espada recta",
  "Thrusting Sword": "Espada de embestida",
  Torch: "Antorcha",
  Twinblade: "Hoja doble",
  Warhammer: "Gran martillo",
  Whip: "Látigo",
};
export { customAttackNames, customAttributeNames, customCategoryNames };
