const customAttackNames = {
  Phy: "Físico",
  Mag: "Magia",
  Fire: "Fuego",
  Ligt: "Rayo",
  Holy: "Sagrado",
  Sor: "Encantamiento",
  Sorc: "Hechicería",
  Crit: "Crítico",
  Rng: "Rango",
  Inc: "Encantamiento",
};

const customAttributeNames = {
  Str: "Fuerza",
  Dex: "Destreza",
  Int: "Inteligencia",
  Fai: "Fe",
  Arc: "Arcano",
  STR: "Fuerza",
  DEX: "Destreza",
  INT: "Inteligencia",
  FAI: "Fe",
  ARC: "Arcano",
};

const customCategoryNames = {
  Axe: "Hacha",
  Bow: "Arco",
  Ballista: "Balista",
  Claw: "Garras",
  "Colossal Sword": "Espada colosal",
  "Colossal Weapon": "Arma colosal",
  Crossbow: "Ballesta",
  "Curved Greatsword": "Espadón curvo",
  "Curved Sword": "Espada curva",
  Dagger: "Daga",
  Fist: "Puños",
  Flail: "Mayal",
  "Glintstone Staff": "Bastón de piedra refulgente",
  Greataxe: "Gran hacha",
  Greatbow: "Arco grande",
  "Great Spear": "Lanza larga",
  Greatsword: "Espadón",
  Halberd: "Alabarda",
  Hammer: "Martillo",
  "Heavy Thrusting Sword": "Espada de embestida pesada",
  "Light Bow": "Arco ligero",
  Reaper: "Guadaña",
  "Sacred Seal": "Sello sagrado",
  Spear: "Lanza",
  "Straight Sword": "Espada recta",
  "Thrusting Sword": "Espada de embestida",
  Torch: "Antorcha",
  Twinblade: "Hoja doble",
  Warhammer: "Gran martillo",
  Whip: "Látigo",
};
const customWeaponNames = {
  "Hand Axe": "Hacha de mano",
  "Jawbone Axe": "Hacha de quijada",
  "Forked Hatchet": "Destral bifurcado",
  "Iron Cleaver": "Machete de hierro",
  "Battle Axe": "Hacha de guerra",
  "Ripple Blade": "Filo semicircular",
  "Icerind Hatchet": "Destral de corteza helada",
  "Sacrificial Axe": "Hacha de sacrificador",
  "Celebrant's Cleaver": "Machete ceremonial",
  "Rosus' Axe": "Hacha de Rosus",
  "Highland Axe": "Hacha de los altiplanos",
  "Warped Axe": "Hacha deforme",
  "Stormhawk Axe": "Hacha de halcón tormentoso",
  "Gargoyle's Black Axe": "Hacha negra de gárgola",
  "Hand Ballista": "Balista de mano",
  "Jar Cannon": "Cañón de tarro",
  Longbow: "Arco largo",
  "Albinauric Bow": "Arco albináurico",
  "Erdtree Bow": "Arco del Árbol Áureo",
  "Horn Bow": "Arco de cuerno",
  "Serpent Bow": "Arco serpentino",
  "Pulley Bow": "Arco de polea",
  "Black Bow": "Arco negro",
  "Bloodhound Claws": "Garras de sabueso",
  "Venomous Fang": "Colmillo ponzoñoso",
  Hookclaws: "Garras punzantes",
  "Raptor Talons": "Garras rapaces",
  "Watchdog's Greatsword": "Espadón de perro guardián",
  Greatsword: "Espadón",
  "Troll's Golden Sword": "Espada dorada de trol",
  "Maliketh's Black Blade": "Hoja negra de Maliketh",
  Zweihander: "Mandoble",
  "Royal Greatsword": "Espadón regio",
  "Godslayer's Greatsword": "Espadón del exterminador de dioses",
  "Grafted Blade Greatsword": "Espadón de hoja injertada",
  "Ruins Greatsword": "Espadón de ruinas",
  "Starscourge Greatsword": "Espadón del Azote de las Estrellas",
  "Troll Knight's Sword": "Espada de caballero trol",
  "Watchdog's Staff": "Bastón de perro guardián",
  "Envoy's Greathorn": "Cuerno grande de emisario",
  "Great Club": "Gran garrote",
  "Prelate's Inferno Crozier": "Báculo infernal de prelado",
  "Duelist Greataxe": "Gran hacha de duelista",
  "Axe Of Godfrey": "Hacha de Godfrey",
  "Dragon Greatclaw": "Gran garra de dragón",
  "Fallingstar Beast Jaw": "Quijada de Bestia de la Estrella fugaz",
  "Staff Of The Avatar": "Bastón de avatar",
  "Ghiza's Wheel": "Rueda de Ghiza",
  "Giant-crusher": "Aplastagigantes",
  "Golem's Halberd": "Alabarda de gólem",
  "Troll's Hammer": "Martillo de trol",
  "Rotten Staff": "Bastón putrefacto",
  "Rotten Greataxe": "Gran hacha putrefacta",
  "Soldier's Crossbow": "Ballesta de soldado",
  "Light Crossbow": "Ballesta ligera",
  "Heavy Crossbow": "Ballesta pesada",
  "Pulley Crossbow": "Ballesta con polea",
  "Full Moon Crossbow": "Ballesta de la Luna Llena",
  "Onyx Lord's Greatsword": "Espadón de Señor de ónice",
  "Crepus's Black-key Crossbow": "Ballesta negra de Crepus",
  Arbalest: "Arbalesta",
  "Bloodhound's Fang": "Colmillo de sabueso",
  Dismounter: "Desmontadora",
  "Magma Wyrm's Scalesword": "Espada de escamas de dragón de magma",
  "Omen Cleaver": "Machete de augurio",
  "Zamor Curved Sword": "Espada curva de Zamor",
  "Monk's Flameblade": "Hoja llameante de monje",
  "Beastman's Cleaver": "Machete de hombre bestia",
  "Morgott's Cursed Sword": "Espada maldita de Morgott",
  Falchion: "Bracamarte",
  Shamshir: "Shamsir",
  "Beastman's Curved Sword": "Espada curva del hombre bestia",
  "Magma Blade": "Hoja de magma",
  "Flowing Curved Sword": "Espada fluvimorfa",
  "Wing Of Astel": "Ala de Astel",
  "Eclipse Shotel": "Shotel del eclipse",
  "Serpent-god's Curved Sword": "Espada curva de dios serpiente",
  "Scavenger's Curved Sword": "Espada curva de saqueador",
  "Mantis Blade": "Hoja de mantis",
  Scimitar: "Cimitarra",
  "Nox Flowing Sword": "Espada fluctuante de Nox",
  Dagger: "Daga",
  Grossmesser: "Grosse messer",
  "Black Knife": "Cuchillo negro",
  "Parrying Dagger": "Daga elusiva",
  Miséricorde: "Misericorde",
  "Crystal Knife": "Cuchillo de cristal",
  "Celebrant's Sickle": "Hoz ceremonial",
  "Glintstone Kris": "Kris de piedra refulgente",
  "Scorpion's Stinger": "Aguijón de escorpión",
  "Great Knife": "Gran cuchillo",
  "Ivory Sickle": "Hoz de marfil",
  "Erdsteel Dagger": "Daga de acero áureo",
  "Blade Of Calling": "Hoja de la invocación",
  "Bloodstained Dagger": "Daga manchada de sangre",
  "Spiked Caestus": "Cestus con pinchos",
  Caestus: "Cestus",
  "Grafted Dragon": "Dragón injertado",
  "Iron Ball": "Bola de hierro",
  "Star Fist": "Puño estrellado",
  "Clinging Bone": "Hueso agarrante",
  "Cipher Pata": "Dandpatta cifrada",
  "Veteran's Prosthesis": "Prótesis de veterano",
  "Nightrider Flail": "Mayal de caballero del ocaso",
  Flail: "Mayal",
  "Family Heads": "Cabezas de familia",
  "Bastard's Stars": "Estrellas del bastardo",
  "Glintstone Staff": "Bastón de piedra refulgente",
  "Crystal Staff": "Bastón de cristal",
  "Chainlink Flail": "Mayal de cadena",
  "Gelmir Glintstone Staff": "Bastón de piedra refulgente de Gelmir",
  "Demi-human Queen's Staff": "Bastón de reina semihumana",
  "Carian Regal Scepter": "Cetro regio cariano",
  "Astrologer's Staff": "Bastón de astrólogo",
  "Digger's Staff": "Bastón del excavador",
  "Prince Of Death's Star": "Bastón del Príncipe de la Muerte",
  "Carian Glintblade Staff": "Bastón de hojas refulgentes cariano",
  "Albinauric Staff": "Bastón albináurico",
  "Academy Glintstone Staff": "Bastón de piedra refulgente de la academia",
  "Carian Glintstone Staff": "Bastón de piedra refulgente cariano",
  "Azur's Glintstone Staff": "Bastón de piedra refulgente de Azur",
  "Lusat's Glintstone Staff": "Bastón de piedra refulgente de Lusat",
  "Meteorite Staff": "Bastón de meteorito",
  "Staff Of The Guilty": "Bastón de condenado",
  "Rotten Crystal Staff": "Bastón de cristal pútrido",
  Greataxe: "Gran hacha",
  "Great Omenkiller Cleaver": "Gran machete de asesino de augurios",
  "Staff Of Loss": "Bastón de la pérdida",
  "Crescent Moon Axe": "Hacha de medialuna",
  "Axe Of Godrick": "Hacha de Godrick",
  "Longhaft Axe": "Hacha de empuñadura larga",
  "Executioner's Greataxe": "Hacha de verdugo",
  "Rusted Anchor": "Ancla oxidada",
  "Winged Greathorn": "Cuerno grande alado",
  "Butchering Knife": "Cuchillo de carnicero sagrado",
  "Gargoyle's Great Axe": "Gran hacha de gárgola",
  "Lion Greatbow": "Arco grande de león",
  "Erdtree Greatbow": "Arco grande del Árbol Áureo",
  "Golem Greatbow": "Arco grande de gólem",
  Greatbow: "Arco grande",
  "Mohgwyn's Sacred Spear": "Lanza sagrada de Mohgwyn",
  "Siluria's Tree": "Árbol de Siluria",
  "Vyke's War Spear": "Lanza de guerra de Vyke",
  "Serpent-hunter": "Cazador de serpientes",
  Lance: "Lanza de justas",
  Treespear: "Lanza arbórea",
  "Bastard Sword": "Espada bastarda",
  "Forked Greatsword": "Espadón bifurcado",
  "Iron Greatsword": "Espadón de hierro",
  "Lordsworn's Greatsword": "Espadón de juramentado",
  "Knight's Greatsword": "Espadón de caballero",
  Flamberge: "Espada flamígera",
  "Ordovis's Greatsword": "Espadón de Ordovis",
  "Alabaster Lord's Sword": "Espada de Señor de alabastro",
  "Banished Knight's Greatsword": "Espadón de caballero proscrito",
  "Dark Moon Greatsword": "Espadón de la luna negra",
  "Sacred Relic Sword": "Espada reliquia sagrada",
  "Helphen's Steeple": "Espira de Helfen",
  "Blasphemous Blade": "Hoja blasfema",
  "Marais Executioner's Sword": "Espada del ejecutor Marais",
  "Sword Of Milos": "Espada de Milos",
  "Golden Order Greatsword": "Espadón de la Orden Dorada",
  "Gargoyle's Greatsword": "Espadón de gárgola",
  "Death's Poker": "Punzadora letal",
  "Gargoyle's Blackblade": "Hoja negra de gárgola",
  "Pest's Glaive": "Guja de la plaga",
  Halberd: "Alabarda",
  Lucerne: "Lucerna",
  "Banished Knight's Halberd": "Alabarda de caballero proscrito",
  "Commander's Standard": "Estandarte de comandante",
  "Ripple Crescent Halberd": "Alabarda de medialuna",
  "Nightrider Glaive": "Guja de caballero del ocaso",
  "Vulgar Militia Saw": "Sierra de carne de cañón",
  "Golden Halberd": "Alabarda dorada",
  Glaive: "Guja",
  "Loretta's War Sickle": "Hoz de guerra de Loretta",
  "Guardian's Swordspear": "Lanza-espada custodia",
  "Dragon Halberd": "Alabarda de dragón",
  "Vulgar Militia Shotel": "Shotel de carne de cañón",
  "Gargoyle's Halberd": "Alabarda de gárgola",
  Mace: "Maza",
  "Gargoyle's Black Halberd": "Alabarda negra de gárgola",
  "Curved Club": "Garrote curvo",
  Warpick: "Pico de guerra",
  Club: "Garrote",
  "Spiked Club": "Garrote con pinchos",
  Hammer: "Martillo",
  "Varré's Bouquet": "Ramo de Varré",
  "Morning Star": "Lucero del alba",
  "Monk's Flamemace": "Maza flamígera de monje",
  "Envoy's Horn": "Cuerno de emisario",
  "Scepter Of The All-knowing": "Cetro del Omnisciente",
  "Nox Flowing Hammer": "Martillo fluctuante de Nox",
  "Ringed Finger": "Dedo anillado",
  "Stone Club": "Garrote de piedra",
  "Marika's Hammer": "Martillo de Márika",
  "Bloody Helice": "Hélice sangrienta",
  "Great Épée": "Gran Épée",
  "Godskin Stitcher": "Punzadora sacroderma",
  "Dragon King's Cragblade": "Hoja rocosa del rey de dragón",
  "Hand Of Malenia": "Mano de Malenia",
  "Meteoric Ore Blade": "Hoja de mineral de meteorito",
  "Rivers Of Blood": "Ríos de sangre",
  Moonveil: "Velo lunar",
  "Dragonscale Blade": "Hoja de Escama de Dragón",
  "Serpentbone Blade": "Hoja de hueso de serpiente",
  Shortbow: "Arco corto",
  "Misbegotten Shortbow": "Arco corto de bastardo",
  "Red Branch Shortbow": "Arco corto de rama roja",
  "Harp Bow": "Arco arpa",
  "Composite Bow": "Arco compuesto",
  Scythe: "Guadaña",
  "Grave Scythe": "Guadaña sepulcral",
  "Halo Scythe": "Guadaña aureolada",
  "Winged Scythe": "Guadaña alada",
  "Finger Seal": "Sello de los Dedos",
  "Godslayer's Seal": "Sello del exterminador de dioses",
  "Giant's Seal": "Sello del gigante",
  "Clawmark Seal": "Sello Marca de Garra",
  "Golden Order Seal": "Sello de la Orden Dorada",
  "Erdtree Seal": "Sello del Árbol Áureo",
  "Dragon Communion Seal": "Sello de la Comunión Dragontina",
  "Frenzied Flame Seal": "Sello de la llama frenética",
  Spear: "Lanza",
  "Short Spear": "Lanza corta",
  "Crystal Spear": "Lanza de cristal",
  "Clayman's Harpoon": "Arpón de hombre de barro",
  Partisan: "Partesana",
  "Celebrant's Rib-rake": "Rejón óseo ceremonial",
  "Cleanrot Spear": "Lanza imputrescible",
  Pike: "Pica",
  Torchpole: "Antorcha alargada",
  "Bolt Of Gransax": "Rayo de Gransax",
  "Cross-naginata": "Naginata cruciforme",
  "Death Ritual Spear": "Lanza ritual fúnebre",
  "Inquisitor's Girandole": "Candelabro de inquisidor",
  "Spiked Spear": "Lanza espinosa",
  "Rotten Crystal Spear": "Lanza de cristal pútrido",
  "Iron Spear": "Lanza de hierro",
  "Winged Spear": "Lanza alada",
  Longsword: "Espada larga",
  "Short Sword": "Espada corta",
  Broadsword: "Espada ancha",
  "Lordsworn's Straight Sword": "Espada recta de juramentado",
  "Weathered Straight Sword": "Espada recta desgastada",
  "Golden Epitaph": "Epitafio dorado",
  "Ornamental Straight Sword": "Espada recta ornamental",
  "Coded Sword": "Espada cifrada",
  "Sword Of Night And Flame": "Espada de la Noche y la Llama",
  "Carian Knight's Sword": "Espada de caballero cariano",
  "Crystal Sword": "Espada de cristal",
  "Sword Of St Trina": "Espada de Santa Trina",
  "Miquellan Knight's Sword": "Espada de caballero de Miquella",
  "Cane Sword": "Espada bastón",
  "Regalia Of Eochaid": "Espada enjoyada de Eochaid",
  "Noble's Slender Sword": "Espada esbelta de noble",
  "Warhawk's Talon": "Garra de halcón de guerra",
  "Rotten Crystal Sword": "Espada de cristal pútrido",
  "Lazuli Glintstone Sword": "Espada de piedra refulgente de Lazuli",
  Estoc: "Ropera",
  Rapier: "Estoque",
  "Cleanrot Knight's Sword": "Espada de caballero imputrescible",
  "Rogier's Rapier": "Estoque de Rogier",
  "Antspur Rapier": "Estoque de aguijón hormigoso",
  "Frozen Needle": "Aguja congelada",
  Torch: "Antorcha",
  "Noble's Estoc": "Ropera de noble",
  "Steel-wire Torch": "Antorcha de acero",
  "St. Trina's Torch": "Antorcha de Santa Trina",
  "Ghostflame Torch": "Antorcha de llama espectral",
  "Beast-repellent Torch": "Antorcha repelente de bestias",
  "Sentry's Torch": "Antorcha de centinela",
  "Godskin Peeler": "Desollador sacrodermo",
  "Twinned Knight Swords": "Espadas gemelas de caballero",
  "Eleonora's Poleblade": "Hoja enastada de Eleonora",
  "Gargoyle's Twinblade": "Hoja doble de gárgola",
  "Gargoyle's Black Blades": "Hojas negras de gárgola",
  "Large Club": "Garrote grande",
  "Greathorn Hammer": "Gran martillo de cuerno",
  "Battle Hammer": "Martillo de guerra",
  "Great Mace": "Gran maza",
  "Curved Great Club": "Gran garrote curvo",
  "Celebrant's Skull": "Cráneo ceremonial",
  "Beastclaw Greathammer": "Gran martillo de garras bestiales",
  Twinblade: "Hoja doble",
  "Envoy's Long Horn": "Cuerno largo de emisario",
  Pickaxe: "Piqueta",
  "Cranial Vessel Candlestand": "Candelabro craneal",
  "Great Stars": "Gran lucero",
  "Devourer's Scepter": "Cetro de devorador",
  "Brick Hammer": "Martillo de piedra",
  Whip: "Látigo",
  "Rotten Battle Hammer": "Martillo de guerra podrido",
  "Thorned Whip": "Látigo con espinas",
  "Magma Whip Candlestick": "Candelabro látigo de magma",
  "Hoslow's Petal Whip": "Látigo con pétalos de Hoslow",
  "Giant's Red Braid": "Trenza roja del gigante",
};
export {
  customAttackNames,
  customAttributeNames,
  customCategoryNames,
  customWeaponNames,
};
