const customAttackNames = {
  Phy: "Físico",
  Mag: "Magia",
  Fire: "Fuego",
  Ligt: "Rayo",
  Holy: "Sagrado",
  Sor: "Encantamiento",
  Sorc: "Hechicería",
  Crit: "Crítico",
  Rng: "Rango",
  Inc: "Encantamiento",
};

const customAttributeNames = {
  Str: "Fuerza",
  Dex: "Destreza",
  Int: "Inteligencia",
  Fai: "Fe",
  Arc: "Arcano",
  STR: "Fuerza",
  DEX: "Destreza",
  INT: "Inteligencia",
  FAI: "Fe",
  ARC: "Arcano",
};

const customCategoryNames = {
  Axe: "Hacha",
  Bow: "Arco",
  Ballista: "Balista",
  Claw: "Garras",
  "Colossal Sword": "Espada colosal",
  "Colossal Weapon": "Arma colosal",
  Crossbow: "Ballesta",
  "Curved Greatsword": "Espadón curvo",
  "Curved Sword": "Espada curva",
  Dagger: "Daga",
  Fist: "Puños",
  Flail: "Mayal",
  "Glintstone Staff": "Bastón de piedra refulgente",
  Greataxe: "Gran hacha",
  Greatbow: "Arco grande",
  "Great Spear": "Lanza larga",
  Greatsword: "Espadón",
  Halberd: "Alabarda",
  Hammer: "Martillo",
  "Heavy Thrusting Sword": "Espada de embestida pesada",
  "Light Bow": "Arco ligero",
  Reaper: "Guadaña",
  "Sacred Seal": "Sello sagrado",
  Spear: "Lanza",
  "Straight Sword": "Espada recta",
  "Thrusting Sword": "Espada de embestida",
  Torch: "Antorcha",
  Twinblade: "Hoja doble",
  Warhammer: "Gran martillo",
  Whip: "Látigo",
};
const customWeaponNames = {
  "Hand Axe": "Hacha de mano",
  "Jawbone Axe": "Hacha de quijada",
  "Forked Hatchet": "Destral bifurcado",
  "Iron Cleaver": "Machete de hierro",
  "Battle Axe": "Hacha de guerra",
  "Ripple Blade": "Filo semicircular",
  "Icerind Hatchet": "Destral de corteza helada",
  "Sacrificial Axe": "Hacha de sacrificador",
  "Celebrant's Cleaver": "Machete ceremonial",
  "Rosus' Axe": "Hacha de Rosus",
  "Highland Axe": "Hacha de los altiplanos",
  "Warped Axe": "Hacha deforme",
  "Stormhawk Axe": "Hacha de halcón tormentoso",
  "Gargoyle's Black Axe": "Hacha negra de gárgola",
  "Hand Ballista": "Balista de mano",
  "Jar Cannon": "Cañón de tarro",
  Longbow: "Arco largo",
  "Albinauric Bow": "Arco albináurico",
  "Erdtree Bow": "Arco del Árbol Áureo",
  "Horn Bow": "Arco de cuerno",
  "Serpent Bow": "Arco serpentino",
  "Pulley Bow": "Arco de polea",
  "Black Bow": "Arco negro",
  "Bloodhound Claws": "Garras de sabueso",
  "Venomous Fang": "Colmillo ponzoñoso",
  Hookclaws: "Garras punzantes",
  "Raptor Talons": "Garras rapaces",
  "Watchdog's Greatsword": "Espadón de perro guardián",
  Greatsword: "Espadón",
  "Troll's Golden Sword": "Espada dorada de trol",
  "Maliketh's Black Blade": "Hoja negra de Maliketh",
  Zweihander: "Mandoble",
  "Royal Greatsword": "Espadón regio",
  "Godslayer's Greatsword": "Espadón del exterminador de dioses",
  "Grafted Blade Greatsword": "Espadón de hoja injertada",
  "Ruins Greatsword": "Espadón de ruinas",
  "Starscourge Greatsword": "Espadón del Azote de las Estrellas",
  "Troll Knight's Sword": "Espada de caballero trol",
  "Watchdog's Staff": "Bastón de perro guardián",
  "Envoy's Greathorn": "Cuerno grande de emisario",
  "Great Club": "Gran garrote",
  "Prelate's Inferno Crozier": "Báculo infernal de prelado",
  "Duelist Greataxe": "Gran hacha de duelista",
  "Axe Of Godfrey": "Hacha de Godfrey",
  "Dragon Greatclaw": "Gran garra de dragón",
  "Fallingstar Beast Jaw": "Quijada de Bestia de la Estrella fugaz",
  "Staff Of The Avatar": "Bastón de avatar",
  "Ghiza's Wheel": "Rueda de Ghiza",
  "Giant-crusher": "Aplastagigantes",
  "Golem's Halberd": "Alabarda de gólem",
  "Troll's Hammer": "Martillo de trol",
  "Rotten Staff": "Bastón putrefacto",
  "Rotten Greataxe": "Gran hacha putrefacta",
  "Soldier's Crossbow": "Ballesta de soldado",
  "Light Crossbow": "Ballesta ligera",
  "Heavy Crossbow": "Ballesta pesada",
  "Pulley Crossbow": "Ballesta con polea",
  "Full Moon Crossbow": "Ballesta de la Luna Llena",
  "Onyx Lord's Greatsword": "Espadón de Señor de ónice",
  "Crepus's Black-key Crossbow": "Ballesta negra de Crepus",
};
export {
  customAttackNames,
  customAttributeNames,
  customCategoryNames,
  customWeaponNames,
};
